ALTER TABLE [dbo].[DI_DOITUONGNHANVIEC]
    ADD CONSTRAINT [FK_DI_DOITUONGNHANVIEC_DI_XULYVB] FOREIGN KEY ([IDXULY]) REFERENCES [dbo].[DI_XULYVB] ([IDXULY]) ON DELETE NO ACTION ON UPDATE NO ACTION;

