ALTER TABLE [dbo].[DEN_DOITUONGNHANVIEC]
    ADD CONSTRAINT [FK_DEN_DOITUONGNHANVIEC_DEN_XULYVB] FOREIGN KEY ([IDXULY]) REFERENCES [dbo].[DEN_XULYVB] ([IDXULY]) ON DELETE NO ACTION ON UPDATE NO ACTION;

