ALTER TABLE [dbo].[DEN_XULYVB]
    ADD CONSTRAINT [PK_DEN_XULYVB] PRIMARY KEY CLUSTERED ([IDXULY] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

