ALTER TABLE [dbo].[DMNHANVIEN]
    ADD CONSTRAINT [PK_DMNHANVIEN] PRIMARY KEY CLUSTERED ([MANV] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

