ALTER TABLE [dbo].[DI_VANBAN]
    ADD CONSTRAINT [PK_DI_VANBAN] PRIMARY KEY CLUSTERED ([IDVB] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

