ALTER TABLE [dbo].[DMCOQUAN]
    ADD CONSTRAINT [PK_DMCOQUAN] PRIMARY KEY CLUSTERED ([MACOQUAN] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

