ALTER TABLE [dbo].[DMPHONGBAN]
    ADD CONSTRAINT [PK_PHONGBAN] PRIMARY KEY CLUSTERED ([MAPHONG] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

