ALTER TABLE [dbo].[THAMSO]
    ADD CONSTRAINT [PK_THAMSO] PRIMARY KEY CLUSTERED ([NAME] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

