ALTER TABLE [dbo].[WS_RECEIVING]
    ADD CONSTRAINT [PK_WS_RECEIVING] PRIMARY KEY CLUSTERED ([IDTRANSFER] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

