ALTER TABLE [dbo].[WS_SENDING]
    ADD CONSTRAINT [PK_WS_SENDING_1] PRIMARY KEY CLUSTERED ([IDFILETRANSFER] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

